In [75]:
import pandas as pd

In [76]:
bbeer_df = pd.read_csv('BoulevardBeers.csv',index_col=None)
bbeer_df = bbeer_df.drop(columns=['Unnamed: 0'])
bbeer_df = bbeer_df.rename(columns={"Type": "Style"})
bbeer_df['BreweryID'] = [1 for i in range(0,len(list(bbeer_df['Name'])))]
bbeer_df

                           Name                        Style   ABV  BreweryID
0                 Ah, Sure Look                  Dark Lager    5.5          1
1                      BLVD ’89                        Lager   4.5          1
2         Bob’s ’47 Oktoberfest         Oktoberfest / Märzen   5.9          1
3              Cranberry Tank 7  Smokestack Limited Release    8.5          1
4                   Dark Crator      Barrel-Aged Dopplebock   12.5          1
..                          ...                          ...   ...        ...
59                     Tenpenny             American Bitter    4.2          1
60         Terror From the Deep                  Double IPA    8.0          1
61                  Tropic Slam             Tart Island Ale    4.2          1
62  Unfiltered Grapefruit Wheat        Hazy American Classic   4.4          1
63                          Zon        Belgian-Style Witbier   4.4          1

[64 rows x 4 columns]

In [77]:
cbbeer_df = pd.read_csv('CityBarrelBeers.csv',index_col=None)
cbbeer_df = cbbeer_df.drop(columns=['Unnamed: 0'])
cbbeer_df = cbbeer_df.rename(columns={"Type": "Style"})
cbbeer_df['BreweryID'] = [2 for i in range(0,len(list(cbbeer_df['Name'])))]
cbbeer_df

,Name,Style,ABV,BreweryID
0,Rad AF,IPA - New England,6.4,2
1,High Society,Lager - American,4.8,2
2,Hell Yeah,Wheat Beer - American Pale Wheat,5.2,2
3,Daydrinker,IPA - New England,6.6,2
4,Space Dragon,IPA - New England,6.0,2
5,Creative Juice,Pale Ale - New England,5.8,2
6,Book Smart,IPA - New England,6.4,2
7,Oktoberfest,Märzen,6.0,2
8,Strawberry Shortcake Bar,IPA - Milkshake,8.5,2
9,Rad Hops of Destiny,IPA - New England,7.3,2
10,Words Are Hard,Bock - Maibock,6.8,2
11,Mango Tango Dreamwave,Sour - Fruited,6.6,2
12,Homestead Peach,Cider - Other Fruit,5.0,2
13,Pineapple Mango Hard Seltzer,Hard Seltzer,4.0,2
14,Crossroads Apfel,Cider - Traditional,7.9,2
15,Fest Bier,Festbier,5.8,2
16,This Meeting Could've Been An Email,IPA - Imperial,7.8,2
17,Sidewalk Surfer,IPA - Imperial,8.0,2

In [78]:
kcbeer_df = pd.read_csv('KcBierCoBeers.csv',index_col=None)
kcbeer_df = kcbeer_df.drop(columns=['Unnamed: 0'])
kcbeer_df = kcbeer_df.rename(columns={"Type": "Style"})
kcbeer_df['BreweryID'] = [3 for i in range(0,len(list(kcbeer_df['Name'])))]
kcbeer_df

              Name                               Style   ABV  BreweryID
0    Bier Co Light          Light German-Style Pilsner  3.50          3
1           Dunkel            Munich-Style Brown Lager  5.00          3
2       Hefeweizen            Bavarian-Style Wheat Ale  5.20          3
3     Helles Lager           Munich-Style Golden Lager  5.10          3
4       Hop Spritz               Hop-Infused Refresher  0.00          3
5    Never Say IPA                      India Pale Ale  5.80          3
6        Pure Pils                German-Style Pilsner  4.80          3
7           Kölsch               Köln-Style Golden Ale  4.80          3
8         Festbier                  Vienna-Style Lager  5.50          3
9      Schwarzbier                         Black Lager  5.00          3
10     Schwarzbock              Black Doppelbock Lager  7.40          3
11       Heim Bier         Bohemian-Style Export Lager  5.50          3
12      Winterbock               Dark Doppelbock Lager  8.25          3
13      Zoigl Bier                         Zoigl Lager  4.80          3
14     Äpfel Cider           Apple Cider (Gluten-Free)  5.00          3
15  ArrowRed Lager  Nürnberg-Style Red Lager (Rotbier)  5.20          3

In [79]:
mcbeer_df = pd.read_csv('MarinCityBeers.csv',index_col = None)
mcbeer_df = mcbeer_df.drop(columns=['Unnamed: 0'])
mcbeer_df = mcbeer_df.rename(columns={"Type": "Style"})
mcbeer_df['BreweryID'] = [4 for i in range(0,len(list(mcbeer_df['Name'])))]
mcbeer_df

                                Name          Style   ABV  BreweryID
0                       Hard Way IPA            IPA   7.5          4
1            Belgian Style Abbey Ale            Ale   7.2          4
2                     Survival Blond            NaN   5.9          4
3             Operation: Yoga Pants             NaN   4.8          4
4                       Hazy Way IPA            IPA   6.4          4
5                       Citrus Wheat          Wheat   5.5          4
6                  Martin City Wheat          Wheat   4.1          4
7                    Fireside Porter            NaN   7.5          4
8                      Winter Warmer  Winter Warmer   7.5          4
9                 Love, Coffee Stout          Stout   6.0          4
10                        Café Blond            NaN   5.3          4
11                 Lemongrass Saison         Saison   4.7          4
12                 Double Berry Sour           Sour   4.8          4
13                         Curveball            NaN   5.6          4
14               Hard Ball Wheat IPA          Wheat   6.5          4
15                 Pink Lemonade Ale            Ale   4.0          4
16                   Irish High Five          Irish   6.0          4
17                       Donut Stout          Stout   6.0          4
18                   Fall Back Brown          Brown   5.4          4
19          Oktoberfest Märzen Lager    Oktoberfest   5.8          4
20                           Pub Ale            Ale   4.8          4
21                       Mocha Stout          Stout   7.5          4
22  Block Party Lemon Strawberry Ale            Ale   4.7          4
23                     Idle Pale Ale            Ale   4.6          4
24                         Shaka IPA            IPA   5.0          4
25                      Easy Way IPA            IPA   5.4          4
26                     Coastline IPA            IPA   7.0          4
27                      Showtime IPA            IPA   6.0          4
28        Double Secret Hard Way IPA            IPA   9.1          4
29                       One Hop IPA            IPA   8.0          4
30         Radical Candor Double IPA            IPA   8.9          4
31                       Jackpot IPA            IPA   7.0          4
32                       King Martin            NaN  10.1          4
33                  Hop House Saison         Saison   7.9          4
34              Bourbon Barrel Abbey            NaN   7.2          4
35                       The Poitier            NaN   9.3          4
36                    Kentucky Friar            NaN  11.8          4
37                 Anniversary Stout          Stout  11.0          4
38            Yes Way José with Lime           with   4.7          4
39                    Rich with Love           with   9.5          4
40                 Old Glory Pilsner        Pilsner   5.0          4
41                 Holiday Apple Ale            Ale   4.8          4
42              Peanut Butter Porter            NaN   5.5          4
43           Forgotten Farmhouse Ale            Ale   6.2          4
44                      Yes Way José            NaN   4.7          4
45                         Apple Ale            Ale   4.8          4
46                 Anniversary Abbey            NaN  13.0          4

In [80]:
beer_df = bbeer_df.append(cbbeer_df, ignore_index=True)
beer_df = beer_df.append(kcbeer_df,ignore_index=True)
beer_df = beer_df.append(mcbeer_df,ignore_index=True)
beer_df

C:\Users\Matt\AppData\Local\Temp\ipykernel_12088\1720724179.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  beer_df = bbeer_df.append(cbbeer_df, ignore_index=True)
C:\Users\Matt\AppData\Local\Temp\ipykernel_12088\1720724179.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  beer_df = beer_df.append(kcbeer_df,ignore_index=True)
C:\Users\Matt\AppData\Local\Temp\ipykernel_12088\1720724179.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  beer_df = beer_df.append(mcbeer_df,ignore_index=True)

                        Name                        Style   ABV  BreweryID
0              Ah, Sure Look                  Dark Lager    5.5          1
1                   BLVD ’89                        Lager   4.5          1
2      Bob’s ’47 Oktoberfest         Oktoberfest / Märzen   5.9          1
3           Cranberry Tank 7  Smokestack Limited Release    8.5          1
4                Dark Crator      Barrel-Aged Dopplebock   12.5          1
..                       ...                          ...   ...        ...
140     Peanut Butter Porter                          NaN   5.5          4
141  Forgotten Farmhouse Ale                          Ale   6.2          4
142             Yes Way José                          NaN   4.7          4
143                Apple Ale                          Ale   4.8          4
144        Anniversary Abbey                          NaN  13.0          4

[145 rows x 4 columns]

In [81]:
beer_df['BeerID'] = [i for i in range(0,len(list(beer_df['Name'])))]
beer_df

,Name,Style,ABV,BreweryID,BeerID
0,"Ah, Sure Look",Dark Lager,5.5,1,0
1,BLVD ’89,Lager,4.5,1,1
2,Bob’s ’47 Oktoberfest,Oktoberfest / Märzen,5.9,1,2
3,Cranberry Tank 7,Smokestack Limited Release,8.5,1,3
4,Dark Crator,Barrel-Aged Dopplebock,12.5,1,4
...,...,...,...,...,...
140,Peanut Butter Porter,NaN,5.5,4,140
141,Forgotten Farmhouse Ale,Ale,6.2,4,141
142,Yes Way José,NaN,4.7,4,142
143,Apple Ale,Ale,4.8,4,143
144,Anniversary Abbey,NaN,13.0,4,144

In [82]:
beer_df.to_csv('Beers.csv',index=False)

## Brewery Info

In [83]:
boulevard_df = pd.read_csv('BoulevardInfo.csv')
city_barrel_df = pd.read_csv('CityBarrelInfo.csv')
kc_bier_df = pd.read_csv('KcBierCoInfo.csv')
martin_city_df = pd.read_csv('MartinCityInfo.csv')

In [84]:
breweries_df = boulevard_df.append(city_barrel_df, ignore_index=True)
breweries_df = breweries_df.append(kc_bier_df, ignore_index=True)
breweries_df = breweries_df.append(martin_city_df, ignore_index=True)
breweries_df = breweries_df.drop(columns=['Unnamed: 0'])
breweries_df

C:\Users\Matt\AppData\Local\Temp\ipykernel_12088\1296935566.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  breweries_df = boulevard_df.append(city_barrel_df, ignore_index=True)
C:\Users\Matt\AppData\Local\Temp\ipykernel_12088\1296935566.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  breweries_df = breweries_df.append(kc_bier_df, ignore_index=True)
C:\Users\Matt\AppData\Local\Temp\ipykernel_12088\1296935566.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  breweries_df = breweries_df.append(martin_city_df, ignore_index=True)

,Name,Address,Contact,BreweryID
0,Boulevard,"2501 Southwest BoulevardKansas City, MO 64108",(816) 474-7095,1
1,City Barrel,"1740 Holmes Street Kansas City, MO 64108",816-298-7008,2
2,KC Bier Co,"310 W 79th StKansas City, MO 64114",(816) 214-8691,3
3,Martin City Brewing Company,"410 E 135th Street, Kansas City, MO 64145",mcbeerclub@gmail.com,4

In [63]:
breweries_df.to_csv('BreweriesInfo.csv',index=False)

## Beers for Sale

In [88]:
plaza_df = pd.read_csv('PlazaStoreBeers.csv',index_col=None)
plaza_df = plaza_df.rename(columns={"Size": "QTY"})
plaza_df['StoreID'] = [1 for i in range(0,len(list(plaza_df['Name'])))]
plaza_df

,Unnamed: 0,Name,QTY,Price,StoreID
0,0,Boulevard Blvr&d Barrel-aged Variety 6pk Bottle,6-Pack 12 Oz,19.99,1
1,1,Boulevard Cinnamon Bun Ale,4-Pack 12 Oz,15.99,1
2,2,Boulevard Dark Truth 6pk,6-Pack 12 Oz,14.99,1
3,3,Boulevard Firestone Walker Ba Wheat Wine Ale,4-Pack 16 Oz,15.29,1
4,4,Boulevard Mango Jungle 6pk,6-Pack 12 Oz,10.49,1
...,...,...,...,...,...
61,61,Kc Bier Co. Fountain City Wheat,6-Pack 12 Oz,11.49,1
62,62,Martin City Fallback Brown 6pk,6-Pack 12 Oz,10.29,1
63,63,Martin City Oktoberfest 6pk,6-Pack 12 Oz,10.49,1
64,64,Martin City Hardway Ipa 6pk Cn,6-Pack 12 Oz,9.99,1
65,65,Martin City Hazy Way Ipa 6pk Cn,6-Pack 12 Oz,10.99,1

In [89]:
gomers_df = pd.read_csv('GomersBeers.csv',index_col=None)
gomers_df = gomers_df.drop(columns=['Unnamed: 0'])
gomers_df['StoreID'] = [2 for i in range(0,len(list(gomers_df['Name'])))]
gomers_df

,Name,QTY,Price,StoreID
0,Boulevard 89 Lager,12pk Can,16.98,2
1,Boulevard Brewing Co Flash Pack,12pk 12 oz,16.98,2
2,Boulevard Brewing Phantom Haze,4pk 16 oz Can,11.98,2
3,Boulevard Brewing Quirk Spiked & Sparkling Pe...,6pk Can,9.99,2
4,Boulevard Brewing Quirk Spiked & Sparkling Se...,12pk Can,16.98,2
5,Boulevard Brewing Quirk Spiked & Sparkling St...,6pk Can,9.99,2
6,Boulevard Cosmic Mix Pack Variety 12oz Cans,12pk Can,16.98,2
7,Boulevard Grapefruit Wheat,12pk 12 oz,16.98,2
8,Boulevard KC Pils - 12oz bottle 6-pack,6pk 12 oz,9.99,2
9,Boulevard Lager 6pk 12z,6pk 12 oz,9.99,2
10,Boulevard Pale Ale,12pk 12 oz,16.98,2
11,Boulevard Pale Ale - 12oz bottle 6-pack,6pk 12 oz,9.99,2
12,Boulevard Pale Ale Cans,12pk 12 oz Can,16.98,2
13,Boulevard Quirk Cherry Blossom 6pk,6pk Can,9.99,2
14,Boulevard Quirk Pineapple Orange 12z,6pk 12 oz,9.99,2
15,Boulevard Quirk Seltzer Citrus Variety 12 Pack,12pk Can,16.98,2
16,Boulevard Quirk Whip Mix Pack 12cn,12pk,16.98,2
17,Boulevard Rye On Rye Whiskey Barrel Aged Ale,4pk 12 oz,14.98,2
18,Boulevard Seasonal 12z,6pk 12 oz,8.99,2
19,Boulevard Single Wide IPA,,9.99 - 16.98,2
20,Boulevard Smoke Pack Dark Truth Stout,6pk 12 oz,13.98,2
21,Boulevard Southwest Blvd,12pk Can,16.98,2
22,Boulevard Space Camper Cosmic IPA - 12oz can ...,12pk 12 oz Can,16.98,2
23,Boulevard Space Camper Cosmic IPA - 12oz can ...,6pk Can,9.99,2
24,Boulevard Tank 7,6pk 12 oz,13.98,2
25,Boulevard Tank 7 Farmhouse Ale,4pk 12 oz Can,13.99,2
26,Boulevard The Calling Double IPA 16oz Cans,4pk 16 oz,12.97,2
27,Boulevard The Sixth Glass,6pk,13.98,2
28,Boulevard Unfiltered Strawberry Wheat Ale Cns,6pk Can,9.99,2
29,Boulevard Unfiltered Wheat Beer - 12oz,6pk 12 oz,9.99,2
30,Boulevard Unfiltered Wheat Beer - 12oz can 12...,12pk 12 oz Can,16.98,2
31,Boulevard Wheat Bottles,12pk 12 oz,16.98,2
32,Boulevard Whiskey Barrel Stout Bottles,4pk,14.98,2
33,Byo Martin City Blonde Local,6pk 12 oz,8.98,2
34,Byo Martin City Hardway IPA Local,6pk,8.98,2
35,City Barrel Adulting 16z,4pk 16 oz,11.99,2
36,City Barrel Beer League 12z,6pk 12 oz Can,10.98,2
37,City Barrel Good Luck 12z,6pk 12 oz Can,10.98,2
38,City Barrel Rad Af 12z,6pk 12 oz Can,14.98,2
39,City Barrel Treat Yo Self 16z,2 Options,18.99 - 19.99,2
40,Kc Bier Bier Box Variety 12 Pack,12pk 12 oz,17.98,2
41,Kc Bier Co Dunkel,6pk,7.97,2
42,Kc Bier Co Hefeweizen Local,6pk,7.97,2
43,Kc Bier Co Helles Local,6pk,7.97,2
44,Kc Bier Dunkel 12 Pack,12pk 12 oz,16.98,2
45,Kc Bier Pils,6pk 12 oz,7.97,2
46,Martin City Cafe Blonde,6pk,8.98,2
47,Martin City Double Berry Sour 12z,6pk 12 oz,8.98,2
48,Martin City Easy Way,6pk,8.98,2

In [90]:
store_df = plaza_df.append(gomers_df,ignore_index=True)
store_df

C:\Users\Matt\AppData\Local\Temp\ipykernel_12088\1170629813.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  store_df = plaza_df.append(gomers_df,ignore_index=True)

,Unnamed: 0,Name,QTY,Price,StoreID
0,0.0,Boulevard Blvr&d Barrel-aged Variety 6pk Bottle,6-Pack 12 Oz,19.99,1
1,1.0,Boulevard Cinnamon Bun Ale,4-Pack 12 Oz,15.99,1
2,2.0,Boulevard Dark Truth 6pk,6-Pack 12 Oz,14.99,1
3,3.0,Boulevard Firestone Walker Ba Wheat Wine Ale,4-Pack 16 Oz,15.29,1
4,4.0,Boulevard Mango Jungle 6pk,6-Pack 12 Oz,10.49,1
...,...,...,...,...,...
110,NaN,Kc Bier Dunkel 12 Pack,12pk 12 oz,16.98,2
111,NaN,Kc Bier Pils,6pk 12 oz,7.97,2
112,NaN,Martin City Cafe Blonde,6pk,8.98,2
113,NaN,Martin City Double Berry Sour 12z,6pk 12 oz,8.98,2
114,NaN,Martin City Easy Way,6pk,8.98,2

In [91]:
beers = beer_df['Name'].unique()
beers

array(['Ah, Sure Look', 'BLVD ’89', 'Bob’s ’47 Oktoberfest',
       'Cranberry Tank 7', 'Dark Crator', 'Frozen Raider', 'Joker’s Wit',
       'Pale Ale', 'Southwest BLVD', 'Space Camper Cosmic IPA',
       'Strawberry Wheat', 'Tank 7', 'Unfiltered Wheat Beer',
       'Berry Noir', 'Bourbon Barrel Quad', 'Dark Truth Stout',
       'Flying Start', 'Rye on Rye', 'Single-Wide IPA', 'The Sixth Glass',
       'Whiskey Barrel Stout', 'Another Round',
       'Barrel-Aged Imperial Porter',
       'Barrel-Aged Imperial Stout And Barleywine Blend',
       'Barrel-Aged Wheat Wine', 'Belgian Abbey-Style', 'Bière De Garde',
       'Brewa Bunga Cove', 'Buck O’Neil – Barrel-Aged Saison',
       'Chocolate Ale (2023)', 'Chocolate-Cherry Dipped', 'Churro Grande',
       'Cinnamon Bun Ale', 'Crème Brûlée', 'Cybersonic C-Hops', 'Dank 7',
       'Dream Vision', 'Five Bourbon Barrel Imperial Stout',
       'Ginger Lemon Radler', 'Irish Ale', 'Magic Drip', 'Mango Jungle',
       'Maple Mood', 'Milk Stout', 'More S’more', 'Nutcracker Ale',
       'Proper Pour', 'Proper Pour – 2023', 'Rum Barrel-Aged Spice Cake',
       'Saison', 'Space Camper Hyper Warp', 'Space Camper Red Spectra',
       'Space Camper | Alpha Vapor', 'Space Camper | Delta Ray IPA',
       'Space Camper | Gigahop IPA', 'Space Camper | Lotus Aura',
       'Space Camper | Nova Flare', 'Space Camper | Star Haze',
       'Teal Rising', 'Tenpenny', 'Terror From the Deep', 'Tropic Slam',
       'Unfiltered Grapefruit Wheat', 'Zon', 'Rad AF', 'High Society',
       'Hell Yeah', 'Daydrinker', 'Space Dragon', 'Creative Juice',
       'Book Smart', 'Oktoberfest', 'Strawberry Shortcake Bar',
       'Rad Hops of Destiny', 'Words Are Hard', 'Mango Tango Dreamwave',
       'Homestead Peach', 'Pineapple Mango Hard Seltzer',
       'Crossroads Apfel', 'Fest Bier',
       "This Meeting Could've Been An Email", 'Sidewalk Surfer',
       'Bier Co Light', 'Dunkel', 'Hefeweizen', 'Helles Lager',
       'Hop Spritz', 'Never Say IPA', 'Pure Pils', 'Kölsch', 'Festbier',
       'Schwarzbier', 'Schwarzbock', 'Heim Bier', 'Winterbock',
       'Zoigl Bier', 'Äpfel Cider', 'ArrowRed Lager', 'Hard Way IPA',
       'Belgian Style Abbey Ale', 'Survival Blond',
       'Operation: Yoga Pants ', 'Hazy Way IPA', 'Citrus Wheat',
       'Martin City Wheat', 'Fireside Porter', 'Winter Warmer',
       'Love, Coffee Stout', 'Café Blond', 'Lemongrass Saison',
       'Double Berry Sour', 'Curveball', 'Hard Ball Wheat IPA',
       'Pink Lemonade Ale', 'Irish High Five', 'Donut Stout',
       'Fall Back Brown', 'Oktoberfest Märzen Lager', 'Pub Ale',
       'Mocha Stout', 'Block Party Lemon Strawberry Ale', 'Idle Pale Ale',
       'Shaka IPA', 'Easy Way IPA', 'Coastline IPA', 'Showtime IPA',
       'Double Secret Hard Way IPA', 'One Hop IPA',
       'Radical Candor Double IPA', 'Jackpot IPA', 'King Martin',
       'Hop House Saison', 'Bourbon Barrel Abbey', 'The Poitier',
       'Kentucky Friar', 'Anniversary Stout', 'Yes Way José with Lime',
       'Rich with Love', 'Old Glory Pilsner', 'Holiday Apple Ale',
       'Peanut Butter Porter', 'Forgotten Farmhouse Ale', 'Yes Way José',
       'Apple Ale', 'Anniversary Abbey'], dtype=object)

In [54]:
for row in store_df.iterrows():
    for beer in beers:
        if beer in row[1]['Name']:
            print(beer)

Cinnamon Bun Ale
Mango Jungle
Pale Ale
Pale Ale
Tropic Slam
Churro Grande
Bourbon Barrel Quad
Dark Crator
Pale Ale
Pale Ale
Frozen Raider
Strawberry Wheat
Strawberry Wheat
Tank 7
Tank 7
Tank 7
Strawberry Shortcake Bar
Creative Juice
Hell Yeah
Space Dragon
Saison
Festbier
Schwarzbock
Dunkel
Hefeweizen
Helles Lager
Bier Co Light
Pure Pils
Oktoberfest
Pale Ale
Pale Ale
Pale Ale
Dark Truth Stout
Space Camper Cosmic IPA
Space Camper Cosmic IPA
Tank 7
Tank 7
The Sixth Glass
Strawberry Wheat
Unfiltered Wheat Beer
Unfiltered Wheat Beer
Whiskey Barrel Stout
Dunkel
Hefeweizen
Dunkel
Double Berry Sour

In [53]:
store_df

,Name,QTY,Price,StoreID
0,Boulevard Blvr&d Barrel-aged Variety 6pk Bottle,6-Pack 12 Oz,19.99,1
1,Boulevard Cinnamon Bun Ale,4-Pack 12 Oz,15.99,1
2,Boulevard Dark Truth 6pk,6-Pack 12 Oz,14.99,1
3,Boulevard Firestone Walker Ba Wheat Wine Ale,4-Pack 16 Oz,15.29,1
4,Boulevard Mango Jungle 6pk,6-Pack 12 Oz,10.49,1
...,...,...,...,...
110,Kc Bier Dunkel 12 Pack,12pk 12 oz,16.98,2
111,Kc Bier Pils,6pk 12 oz,7.97,2
112,Martin City Cafe Blonde,6pk,8.98,2
113,Martin City Double Berry Sour 12z,6pk 12 oz,8.98,2
114,Martin City Easy Way,6pk,8.98,2

In [92]:
store_df.to_csv('BeersForSale.csv',index = False)

## Store info

In [97]:
gomers_df = pd.read_csv('GomersInfo.csv')
gomers_df

      Name                               Address         Contact  StoreID
0  Gomer's  6298 Missouri 9, Parkville, MO 64152  (816) 746-0400        1

In [99]:
plaza_df = pd.read_csv('PlazaInfo.csv')
plaza_df

,Name,Address,Contact,StoreID
0,Plaza Liquor,"4500 Belleview Avenue, Kansas City, MO 64111",(816) 531-5900,2

In [100]:
store_info = gomers_df.append(plaza_df, ignore_index=True)
store_info

C:\Users\Matt\AppData\Local\Temp\ipykernel_12088\2503787176.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  store_info = gomers_df.append(plaza_df, ignore_index=True)

,Name,Address,Contact,StoreID
0,Gomer's,"6298 Missouri 9, Parkville, MO 64152",(816) 746-0400,1
1,Plaza Liquor,"4500 Belleview Avenue, Kansas City, MO 64111",(816) 531-5900,2

In [101]:
store_info.to_csv('StoreInfo.csv',index = False)